import { html, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import type { FileEntry } from "../../api/types";
import { store } from "../../state";
import { formatBytes } from "../../utils/format";
import { OmbPureElement } from "./omb-element";

const MEDIA_ICON = { image: "image", raw: "aperture", video: "film", other: "file" } as const;
const queue: (() => Promise<void>)[] = [];
let active = 0;

/** Limits concurrent thumbnail generation so a big grid doesn't flood the backend. */
function schedule(task: () => Promise<void>) {
  queue.push(task);
  const next = () => {
    if (active >= 4 || !queue.length) return;
    active++;
    void queue.shift()!().finally(() => {
      active--;
      next();
    });
  };
  next();
}

/** Lazy thumbnail tile: generated by the backend once scrolled into view. */
@customElement("omb-thumbnail")
export class OmbThumbnail extends OmbPureElement {
  @property({ attribute: false }) file!: FileEntry;
  @state() private src: string | null = null;
  #observer?: IntersectionObserver;

  override connectedCallback(): void {
    super.connectedCallback();
    this.#observer = new IntersectionObserver((entries) => {
      if (!entries.some((e) => e.isIntersecting)) return;
      this.#observer?.disconnect();
      const path = this.file.abs_path;
      if (path && this.file.media !== "other") {
        schedule(async () => {
          this.src = await store.backend.thumbnail(path).catch(() => null);
        });
      }
    });
    this.#observer.observe(this);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.#observer?.disconnect();
  }

  override render() {
    const f = this.file;
    const tone = f.category === "error" ? "ring-2 ring-error" : f.category === "ignored" ? "opacity-50" : "";
    return html`
      <figure class="flex flex-col gap-1" title=${f.error ?? f.target_path ?? f.rel_path}>
        <div class="relative aspect-[3/2] rounded-field overflow-hidden bg-base-300 grid place-items-center ${tone}">
          ${this.src
            ? html`<img src=${this.src} alt=${f.name} loading="lazy" class="absolute inset-0 size-full object-cover" />`
            : html`<omb-icon name=${MEDIA_ICON[f.media]} class="size-6 text-base-content/40"></omb-icon>`}
          ${f.media === "video" ? html`<span class="absolute bottom-1 right-1 badge badge-xs badge-neutral">VIDEO</span>` : nothing}
          ${f.media === "raw" ? html`<span class="absolute bottom-1 right-1 badge badge-xs badge-neutral">RAW</span>` : nothing}
        </div>
        <figcaption class="text-xs truncate">${f.name}<span class="text-base-content/50"> · ${formatBytes(f.size)}</span></figcaption>
      </figure>
    `;
  }
}
